# i'm using `port install google_appengine`
GOOGLE_APPENGINE_PATH = /opt/local/share/google_appengine

server:
	python $(GOOGLE_APPENGINE_PATH)/dev_appserver.py .

deploy:
	python $(GOOGLE_APPENGINE_PATH)/appcfg.py update .